TALENT_RARITY_COMMON = 1
TALENT_RARITY_RARE = 2
TALENT_RARITY_EPIC = 4

RARITY_TEXT_TO_NUMBER = {
	common = TALENT_RARITY_COMMON,
	rare = TALENT_RARITY_RARE,
	epic = TALENT_RARITY_EPIC,
}

TALENTS_TYPE = {
	ABILITY = 1,
}

TALENT_OPERATOR = {
	ADD = 1,
	MULTIPLY = 2,
}

OPERATOR_TEXT_TO_NUMBER = {
	ADD = TALENT_OPERATOR.ADD,
	MULTIPLY = TALENT_OPERATOR.MULTIPLY,
}

DEFAULT_MULTIPLICATION_TARGET = 100
 