TELEPORT_COOLDOWN = 9

SPHERE_MOVESPEED = 15
SPHERE_HEAL = 10
SPHERE_COOLDOWN = 3
SPHERE_SHIELD_MAGICAL_RESISTANCE = 6
SPHERE_SHIELD_ARMOR = 3
SPHERE_SHIELD_DECRASE_MAGIC_RESIST = 6
SPHERE_SHIELD_PHYSIC = 500
SPHERE_SHIELD_PHYSIC_COOLDOWN = 20
SPHERE_SHIELD_MAGICAL = 500
SPHERE_SHIELD_MAGICAL_COOLDOWN = 20
SPHERE_SHIELD_ALL = 550
SPHERE_SHIELD_ALL_COOLDOWN = 20

SPHERE_RADIANCE_RADIUS = 450
SPHERE_RADIANCE_DAMAGE = 35

SPHERE_MISS = 5
SPHERE_SPELL_RADIUS = 10
 

BUYBACK_COOLDOWN = 240
-- Настройки WARSONG

if GetMapName() == "warsong" then
    RESPAWN_TIME = 10

    START_GOLD = 600
    HERO_STARTING_LEVEL = 1
    GRANT_INTERVAL = 60
    GRANT_LEVELS = 0
    GRANT_GOLD = 550

    CONDITION_FLAG_COUNT_WIN = 8

    FLAG_RETURN_RADIUS = 245
    FLAG_RETURN_DURATION = 4
    FLAG_AUTO_RETURN_DURATION = 45

    GOOD_FLAG_SCALE = 0.9
    BAD_FLAG_SCALE = 0.9
    FLAG_PICKUP_SCALE = 0.8

    BONUS_SPEED = 20
    FLAG_BONUS_SPEED = 5
    MAX_SPEED = 650
    FLAG_CARRIER_MAX_SPEED = 390

    BAN_TIME = 3 -- Время на бан

    DAY_NIGHT_CYCL = false -- Включение / выключение смены для и ночи

    FOUNTAIN_MAX_HEALTH_REGEN_PCT = 30
    FOUNTAIN_MAX_MANA_REGEN_PCT = 22

    PORTAL_COOLDOWN = 0.6

    RUNE_INTERVAL = 120

    NEUTRAL_ITEM_TIMINGS = 
    {
        TIER_1 = 150, -- 0:00
        TIER_2 = 350, -- 3:30
        TIER_3 = 500, -- 9:00   
        TIER_4 = 720, -- 12:00
        TIER_5 = 820, -- 15:00
    }
    -- Магический и физический резист
    RESISTANCE_TIME_ACTIVATED = 10 -- Время когда он начинается (мин.)
    MAGICAL_RESISTANCE_PERCENTAGE = 10
    PHYSICAL_RESISTANCE_PERCENTAGE = 10

    -- Время до новых способностей
    NEW_ABILITY_COOLDOWN = 5400
    NEW_ULTIMATE_COOLDOWN = 270
    REROLL_ABILITIES_MAX_COUNT_NOT_ULTI = 1 -- РЕРОЛЛОВ ДЛЯ ОБЫЧНЫХ СПОСОБНОСТЕЙ 
    REROLL_ABILITIES_MAX_COUNT_ULTI = 1 -- РЕРОЛЛОВ ДЛЯ УЛЬТИМЕЙТОВ

    -- Настройка шаров
    NEW_PASSIVE_SPELLS_COOLDOWN = 289 -- 420s / 7m
    MAX_COUNT_CHOOSE_PASSIVE_SPELL_IN_GAME = 3
    
    -- One Punchman
    ONE_PUNCHMAN_SETTINGS_CHANCE = {2,3,3}
    ONE_PUNCHMAN_SETTINGS_CHANCE_SOUL = {8,10,20}
    ONE_PUNCHMAN_SETTINGS_COOLDOWN = 80
    ONE_PUNCHMAN_SETTINGS_COOLDOWN_KILL = 60
    ONE_PUNCHMAN_SETTINGS_DURATION = 20
    ONE_PUNCHMAN_SETTINGS_ATTACK_SPEED = {60,80,95} 
    ONE_PUNCHMAN_SETTINGS_LIFESTEAL = {10,12,22}
    SETTINGS_ONE_PUNCHMAN_RESPAWN_FAST_MULTIPLE = 3

    -- Murder
    MURDER_SETTINGS_CRITICAL_CHANCE_DOUBLE = {15,20,30}
    MURDER_SETTINGS_CRITICAL_CHANCE_TRIPPLE = {8,12,16}
    MURDER_SETTINGS_CRITICAL_CHANCE_FOUR = {7,8,11}
    MURDER_SETTINGS_KILL_REFRESH_LAST_SPELL = {12,17,23}

    -- Defender
    DEFENDER_SETTINGS_REFLECT_CHANCE = {15,20,29}
    DEFENDER_SETTINGS_EVASION_CHANCE = {12,20,25}
    DEFENDER_BUFF_CHANCE = {12,20,25}
    DEFENDER_SETTINGS_MAGICAL_RESISTANCE = 45
    DEFENDER_SETTINGS_ARMOR = 55
    DEFENDER_SETTINGS_INCREASE_hEAL = 190
    DEFENDER_SETTINGS_DURATION_BONUS = {11,13,15}
    DEFENDER_SETTINGS_COOLDOWN = 25
    DEFENDER_SETTINGS_SHIELD_CHANCE = {15,18,23}
    DEFENDER_SETTINGS_BLOCK_DAMAGE = 650
    DEFENDER_SETTINGS_ROOTED_DURATION = 2
    DEFENDER_SETTINGS_ROOTED_RADIUS = 700
    DEFENDER_SETTINGS_SHIELD_DURATION = {10,15,20}

    -- Immortal
    IMMORTAL_SETTINGS_CHANCE_RESPAWN = {13,20,23}
    IMMORTAL_SETTINGS_CHANCE_EXPLOSION = {35,45,50}
    IMMORTAL_SETTINGS_DAMAGE = {720,890,1400}
    IMMORTAL_SETTINGS_CHANCE_BKB = {10,20,30}
    IMMORTAL_SETTINGS_DURATION_BKB = {2,3,4}
    IMMORTAL_SETTINGS_COOLDOWN_BKB = {60,60,60}

    -- Himaron
    HIMARON_SETTINGS_CHANCE = {20,35,50}
    HIMARON_SETTINGS_DAMAGE = 150
    HIMARON_SETTINGS_MOVESPEED = 150
    HIMARON_SETTINGS_COOLDOWN_REDUCTION = 38
    HIMARON_SETTINGS_SPELL_AMPLIFY = 25
    HIMARON_SETTINGS_PURE_DAMAGE_INCREASE = {25,35,45}
    HIMARON_SETTINGS_COOLDOWN = 50
    HIMARON_SETTINGS_DURATION = 15
    DEMON_SETTINGS_CHANCE = {15,18,30}
    DEMON_SETTINGS_MIN_DAMAGE = {550,850,1200}
    DEMON_SETTINGS_MAX_DAMAGE = {640,930,1800}
    DEMON_SETTINGS_INCREASE_DAMAGE_SELF = 20
    HIMARON_SWORD_COOLDOWN = 23

    -- Процент получения
    PERCENT_OF_LEVEL_MINUTE = 210

    REROLL_SPHERES = 1
    NEW_SPHERES = 240
    MAX_SPHERE_LEVEL = 4
    COUNT_SPHERE_CHOICE = 2
    MAX_SPHERE_COUNT = 14

end

-- Настройки DASH
if GetMapName() == "dash" then
    RESPAWN_TIME = 10

    START_GOLD = 600
    HERO_STARTING_LEVEL = 1
    GRANT_INTERVAL = 60
    GRANT_LEVELS = 0
    GRANT_GOLD = 300

    CONDITION_FLAG_COUNT_WIN = 7

    FLAG_RETURN_RADIUS = 245
    FLAG_RETURN_DURATION = 3
    FLAG_AUTO_RETURN_DURATION = 45

    GOOD_FLAG_SCALE = 0.9
    BAD_FLAG_SCALE = 0.9
    FLAG_PICKUP_SCALE = 0.8

    BONUS_SPEED = 20
    FLAG_BONUS_SPEED = 5
    MAX_SPEED = 550
    FLAG_CARRIER_MAX_SPEED = 400

    BAN_TIME = 5 -- Время на бан

    DAY_NIGHT_CYCL = false -- Включение / выключение смены для и ночи

    FOUNTAIN_MAX_HEALTH_REGEN_PCT = 20
    FOUNTAIN_MAX_MANA_REGEN_PCT = 15

    PORTAL_COOLDOWN = 0.6

    RUNE_INTERVAL = 120

    NEUTRAL_ITEM_TIMINGS = 
    {
        TIER_1 = 200, -- 0:00
        TIER_2 = 350, -- 3:30
        TIER_3 = 650, -- 9:00 
        TIER_4 = 750, -- 12:00
        TIER_5 = 1000, -- 15:00
    }
    
    TIME_FOR_AMP_TOWERS_AND_CREEPS = 450  --- 5 мин | время когда крипы и башни усиляются
    -- КРИПЫ:
    HEALTH_AMP_CREEPS = 10 -- бафф на здоровье крипов | 35%
    DAMAGE_AMP_CREEPS = 38 -- 5афф на урон крипов | 35%
    ARMOR_AMP_CREEPS = 40 --афф на броню крипов | 35%
    -- БАШНИ И ТРОН:
    HEALTH_AMP_TOWERS = 2 -- бафф на здоровье башен | 35%
    DAMAGE_AMP_TOWERS = 35 -- бафф на урон башен | 35%
    ARMOR_AMP_TOWERS = 2 -- бафф на броню башен | 35%

    -- Магический и физический резист
    RESISTANCE_TIME_ACTIVATED = 300 -- Время когда он начинается (мин.)
    MAGICAL_RESISTANCE_PERCENTAGE = 10
    PHYSICAL_RESISTANCE_PERCENTAGE = 10

    -- Время до новых способностей
    NEW_ABILITY_COOLDOWN = 5400
    NEW_ULTIMATE_COOLDOWN = 270 -- 5 мин
    REROLL_ABILITIES_MAX_COUNT_NOT_ULTI = 1 -- РЕРОЛЛОВ ДЛЯ ОБЫЧНЫХ СПОСОБНОСТЕЙ 
    REROLL_ABILITIES_MAX_COUNT_ULTI = 1 -- РЕРОЛЛОВ ДЛЯ УЛЬТИМЕЙТОВ

    -- Настройка судеб
    NEW_PASSIVE_SPELLS_COOLDOWN = 300 -- 420s / 7m
    MAX_COUNT_CHOOSE_PASSIVE_SPELL_IN_GAME = 3
    
    -- One Punchman
    ONE_PUNCHMAN_SETTINGS_CHANCE = {1,2,3}
    ONE_PUNCHMAN_SETTINGS_CHANCE_SOUL = {8,10,20}
    ONE_PUNCHMAN_SETTINGS_COOLDOWN = 50
    ONE_PUNCHMAN_SETTINGS_COOLDOWN_KILL = 80
    ONE_PUNCHMAN_SETTINGS_DURATION = 20
    ONE_PUNCHMAN_SETTINGS_ATTACK_SPEED = {50,70,90} 
    ONE_PUNCHMAN_SETTINGS_LIFESTEAL = {10,12,22}
    SETTINGS_ONE_PUNCHMAN_RESPAWN_FAST_MULTIPLE = 2

    -- Murder
    MURDER_SETTINGS_CRITICAL_CHANCE_DOUBLE = {10,20,30}
    MURDER_SETTINGS_CRITICAL_CHANCE_TRIPPLE = {8,12,16}
    MURDER_SETTINGS_CRITICAL_CHANCE_FOUR = {7,8,11}
    MURDER_SETTINGS_KILL_REFRESH_LAST_SPELL = {12,17,23}

    -- Defender
    DEFENDER_SETTINGS_REFLECT_CHANCE = {15,20,29}
    DEFENDER_SETTINGS_EVASION_CHANCE = {12,20,25}
    DEFENDER_BUFF_CHANCE = {12,20,25}
    DEFENDER_SETTINGS_MAGICAL_RESISTANCE = 45
    DEFENDER_SETTINGS_ARMOR = 45
    DEFENDER_SETTINGS_INCREASE_hEAL = 150
    DEFENDER_SETTINGS_DURATION_BONUS = {11,13,15}
    DEFENDER_SETTINGS_COOLDOWN = 25
    DEFENDER_SETTINGS_SHIELD_CHANCE = {15,18,23}
    DEFENDER_SETTINGS_BLOCK_DAMAGE = 550
    DEFENDER_SETTINGS_ROOTED_DURATION = 2
    DEFENDER_SETTINGS_ROOTED_RADIUS = 700
    DEFENDER_SETTINGS_SHIELD_DURATION = {10,15,20}

    -- Immortal
    IMMORTAL_SETTINGS_CHANCE_RESPAWN = {13,20,23}
    IMMORTAL_SETTINGS_CHANCE_EXPLOSION = {45,50,55}
    IMMORTAL_SETTINGS_DAMAGE = {440,770,1300}
    IMMORTAL_SETTINGS_CHANCE_BKB = {10,20,30}
    IMMORTAL_SETTINGS_DURATION_BKB = {3,4,4}
    IMMORTAL_SETTINGS_COOLDOWN_BKB = {55,55,55}

    -- Himaron
    HIMARON_SETTINGS_CHANCE = {15,25,35}
    HIMARON_SETTINGS_DAMAGE = 110
    HIMARON_SETTINGS_MOVESPEED = 150
    HIMARON_SETTINGS_COOLDOWN_REDUCTION = 35
    HIMARON_SETTINGS_SPELL_AMPLIFY = 35
    HIMARON_SETTINGS_PURE_DAMAGE_INCREASE = {25,30,40}
    HIMARON_SETTINGS_COOLDOWN = 40
    HIMARON_SETTINGS_DURATION = 13
    DEMON_SETTINGS_CHANCE = {15,18,30}
    DEMON_SETTINGS_MIN_DAMAGE = {450,850,1300}
    DEMON_SETTINGS_MAX_DAMAGE = {540,930,1700}
    DEMON_SETTINGS_INCREASE_DAMAGE_SELF = 20
    HIMARON_SWORD_COOLDOWN = 14

    -- Время за сколько в сумме будет 30 лвл  в минутах
    PERCENT_OF_LEVEL_MINUTE = 90

    -- Время возрождения для dash
    -- уровень, время респавна
    DASH_RESPAWN_TIME_LEVEL = 
    {
        {8, 10},
        {15, 15},
        {28, 28},
        {30, 60},
    }

    REROLL_SPHERES = 1
    NEW_SPHERES = 400
    MAX_SPHERE_LEVEL = 3
    COUNT_SPHERE_CHOICE = 2
    MAX_SPHERE_COUNT = 10
    -- таверы которые нужно снести чтобы можно было сломать центральную башню для радиант 
    tower_to_kills_for_radiant = {
        ["npc_dota_badguys_tower2_bot"] = 2,
        ["npc_dota_badguys_tower2_top"] = 2,
        ["npc_dota_badguys_tower3_top"] = 1,
        ["npc_dota_badguys_tower3_bot"] = 1, 
    }
    -- таверы которые нужно снести чтобы можно было сломать центральную башню для даер 
    tower_to_kills_for_dire = {
        ["npc_dota_goodguys_tower2_top"] = 2,
        ["npc_dota_goodguys_tower2_bot"] = 2,
        ["npc_dota_goodguys_tower3_bot"] = 1,
        ["npc_dota_goodguys_tower3_top"] = 1
    }

end

-- Настройки PORTAL DUO
if GetMapName() == "portal_duo" then
    RESPAWN_TIME = 6

    START_GOLD = 700
    HERO_STARTING_LEVEL = 1
    GRANT_INTERVAL = 60
    GRANT_LEVELS = 0
    GRANT_GOLD = 1200

    CONDITION_FLAG_COUNT_WIN = 57 -- Количество убийств для победы в дуо прикрепил к переменной с флагами

    BAN_TIME = 6 -- Время на бан

    GOOD_FLAG_SCALE = 0.9
    BAD_FLAG_SCALE = 0.9
    FLAG_PICKUP_SCALE = 0.8

    BONUS_SPEED = 35
    FLAG_BONUS_SPEED = 5
    MAX_SPEED = 750
    FLAG_CARRIER_MAX_SPEED = 400

    FOUNTAIN_MAX_HEALTH_REGEN_PCT = 30
    FOUNTAIN_MAX_MANA_REGEN_PCT = 25

    DAY_NIGHT_CYCL = false -- Включение / выключение смены для и ночи

    PORTAL_COOLDOWN = 0.8

    RUNE_INTERVAL = 120

    NEUTRAL_ITEM_TIMINGS = 
    {
        TIER_1 = 150, -- 0:00
        TIER_2 = 350, -- 3:30
        TIER_3 = 500, -- 9:00   
        TIER_4 = 720, -- 12:00
        TIER_5 = 820, -- 15:00
    }

    -- Магический и физический резист
    RESISTANCE_TIME_ACTIVATED = 10 -- Время когда он начинается (мин.)
    MAGICAL_RESISTANCE_PERCENTAGE = 10
    PHYSICAL_RESISTANCE_PERCENTAGE = 10

    -- Время до новых способностей
    NEW_ABILITY_COOLDOWN = 5400
    NEW_ULTIMATE_COOLDOWN = 270 -- 5 мин
    REROLL_ABILITIES_MAX_COUNT_NOT_ULTI = 1 -- РЕРОЛЛОВ ДЛЯ ОБЫЧНЫХ СПОСОБНОСТЕЙ 
    REROLL_ABILITIES_MAX_COUNT_ULTI = 1 -- РЕРОЛЛОВ ДЛЯ УЛЬТИМЕЙТОВ

    -- Настройка шаров
    NEW_PASSIVE_SPELLS_COOLDOWN = 289 --420 -- 420s / 7m
    MAX_COUNT_CHOOSE_PASSIVE_SPELL_IN_GAME = 3

    -- One Punchman
    ONE_PUNCHMAN_SETTINGS_CHANCE = {1,1,2}
    ONE_PUNCHMAN_SETTINGS_CHANCE_SOUL = {8,10,20}
    ONE_PUNCHMAN_SETTINGS_COOLDOWN = 35
    ONE_PUNCHMAN_SETTINGS_COOLDOWN_KILL = 90
    ONE_PUNCHMAN_SETTINGS_DURATION = 20
    ONE_PUNCHMAN_SETTINGS_ATTACK_SPEED = {60,70,80} 
    ONE_PUNCHMAN_SETTINGS_LIFESTEAL = {10,12,22}
    SETTINGS_ONE_PUNCHMAN_RESPAWN_FAST_MULTIPLE = 2

    -- Murder
    MURDER_SETTINGS_CRITICAL_CHANCE_DOUBLE = {15,20,30}
    MURDER_SETTINGS_CRITICAL_CHANCE_TRIPPLE = {8,12,16}
    MURDER_SETTINGS_CRITICAL_CHANCE_FOUR = {7,8,11}
    MURDER_SETTINGS_KILL_REFRESH_LAST_SPELL = {16,20,23}

    -- Defender
    DEFENDER_SETTINGS_REFLECT_CHANCE = {15,20,29}
    DEFENDER_SETTINGS_EVASION_CHANCE = {12,20,25}
    DEFENDER_BUFF_CHANCE = {12,20,25}
    DEFENDER_SETTINGS_MAGICAL_RESISTANCE = 45
    DEFENDER_SETTINGS_ARMOR = 55
    DEFENDER_SETTINGS_INCREASE_hEAL = 150
    DEFENDER_SETTINGS_DURATION_BONUS = {11,13,15}
    DEFENDER_SETTINGS_COOLDOWN = 27
    DEFENDER_SETTINGS_SHIELD_CHANCE = {15,18,23}
    DEFENDER_SETTINGS_BLOCK_DAMAGE = 650
    DEFENDER_SETTINGS_ROOTED_DURATION = 2
    DEFENDER_SETTINGS_ROOTED_RADIUS = 700
    DEFENDER_SETTINGS_SHIELD_DURATION = {10,15,20}

    -- Immortal
    IMMORTAL_SETTINGS_CHANCE_RESPAWN = {13,20,23}
    IMMORTAL_SETTINGS_CHANCE_EXPLOSION = {35,45,50}
    IMMORTAL_SETTINGS_DAMAGE = {720,890,1400}
    IMMORTAL_SETTINGS_CHANCE_BKB = {10,20,30}
    IMMORTAL_SETTINGS_DURATION_BKB = {2,3,4}
    IMMORTAL_SETTINGS_COOLDOWN_BKB = {60,55,50}

    -- Himaron
    HIMARON_SETTINGS_CHANCE = {20,35,50}
    HIMARON_SETTINGS_DAMAGE = 150
    HIMARON_SETTINGS_MOVESPEED = 150
    HIMARON_SETTINGS_COOLDOWN_REDUCTION = 30
    HIMARON_SETTINGS_SPELL_AMPLIFY = 25
    HIMARON_SETTINGS_PURE_DAMAGE_INCREASE = {25,35,45}
    HIMARON_SETTINGS_COOLDOWN = 16
    HIMARON_SETTINGS_DURATION = 12
    DEMON_SETTINGS_CHANCE = {15,22,35}
    DEMON_SETTINGS_MIN_DAMAGE = {550,850,1200}
    DEMON_SETTINGS_MAX_DAMAGE = {640,930,1800}
    DEMON_SETTINGS_INCREASE_DAMAGE_SELF = 20
    HIMARON_SWORD_COOLDOWN = 15

    -- Время за сколько в сумме будет 30 лвл  в минутах
    PERCENT_OF_LEVEL_MINUTE = 210

    -- Сколько дают доп. киллов за нажатие на старте
    HOW_MUCH_KILLS_ADD = 2

    DASH_RESPAWN_TIME_LEVEL = 
    {
        {8, 6},
        {15, 8},
        {28, 10},
        {30, 10},
    }

    REROLL_SPHERES = 1
    NEW_SPHERES = 220
    MAX_SPHERE_LEVEL = 4
    COUNT_SPHERE_CHOICE = 2
    MAX_SPHERE_COUNT = 14

 

end

if GetMapName() == "portal_trio" then
    RESPAWN_TIME = 6

    START_GOLD = 700
    HERO_STARTING_LEVEL = 1
    GRANT_INTERVAL = 60
    GRANT_LEVELS = 0
    GRANT_GOLD = 1200

    CONDITION_FLAG_COUNT_WIN = 50 -- Количество убийств для победы в дуо прикрепил к переменной с флагами

    FLAG_RETURN_RADIUS = 238
    FLAG_RETURN_DURATION = 4
    FLAG_AUTO_RETURN_DURATION = 45

    BAN_TIME = 5 -- Время на бан

    GOOD_FLAG_SCALE = 0.9
    BAD_FLAG_SCALE = 0.9
    FLAG_PICKUP_SCALE = 0.8

    BONUS_SPEED = 35
    FLAG_BONUS_SPEED = 5
    MAX_SPEED = 750
    FLAG_CARRIER_MAX_SPEED = 400

    FOUNTAIN_MAX_HEALTH_REGEN_PCT = 30
    FOUNTAIN_MAX_MANA_REGEN_PCT = 22

    DAY_NIGHT_CYCL = false -- Включение / выключение смены для и ночи

    PORTAL_COOLDOWN = 0.6

    RUNE_INTERVAL = 120

    NEUTRAL_ITEM_TIMINGS = 
    {
        TIER_1 = 100, -- 0:00
        TIER_2 = 250, -- 3:30
        TIER_3 = 450, -- 9:00
        TIER_4 = 640, -- 12:00
        TIER_5 = 800, -- 15:00
    }

    -- Магический и физический резист
    RESISTANCE_TIME_ACTIVATED = 10 -- Время когда он начинается (мин.)
    MAGICAL_RESISTANCE_PERCENTAGE = 10
    PHYSICAL_RESISTANCE_PERCENTAGE = 10

    -- Время до новых способностей
    NEW_ABILITY_COOLDOWN = 5400
    NEW_ULTIMATE_COOLDOWN = 270
    REROLL_ABILITIES_MAX_COUNT_NOT_ULTI = 1 -- РЕРОЛЛОВ ДЛЯ ОБЫЧНЫХ СПОСОБНОСТЕЙ 
    REROLL_ABILITIES_MAX_COUNT_ULTI = 1 -- РЕРОЛЛОВ ДЛЯ УЛЬТИМЕЙТОВ

    -- Настройка шаров
    NEW_PASSIVE_SPELLS_COOLDOWN = 289 --420 -- 420s / 7m
    MAX_COUNT_CHOOSE_PASSIVE_SPELL_IN_GAME = 3

    -- One Punchman
    ONE_PUNCHMAN_SETTINGS_CHANCE = {1,2,3}
    ONE_PUNCHMAN_SETTINGS_CHANCE_SOUL = {8,10,20}
    ONE_PUNCHMAN_SETTINGS_COOLDOWN = 35
    ONE_PUNCHMAN_SETTINGS_COOLDOWN_KILL = 80
    ONE_PUNCHMAN_SETTINGS_DURATION = 20
    ONE_PUNCHMAN_SETTINGS_ATTACK_SPEED = {60,80,95} 
    ONE_PUNCHMAN_SETTINGS_LIFESTEAL = {10,12,22}
    SETTINGS_ONE_PUNCHMAN_RESPAWN_FAST_MULTIPLE = 2

    -- Murder
    MURDER_SETTINGS_CRITICAL_CHANCE_DOUBLE = {15,20,30}
    MURDER_SETTINGS_CRITICAL_CHANCE_TRIPPLE = {8,12,16}
    MURDER_SETTINGS_CRITICAL_CHANCE_FOUR = {7,8,11}
    MURDER_SETTINGS_KILL_REFRESH_LAST_SPELL = {16,20,23}

    -- Defender
    DEFENDER_SETTINGS_REFLECT_CHANCE = {15,20,38}
    DEFENDER_SETTINGS_EVASION_CHANCE = {12,20,25}
    DEFENDER_BUFF_CHANCE = {14,20,30}
    DEFENDER_SETTINGS_MAGICAL_RESISTANCE = 45
    DEFENDER_SETTINGS_ARMOR = 55
    DEFENDER_SETTINGS_INCREASE_hEAL = 160
    DEFENDER_SETTINGS_DURATION_BONUS = {11,13,15}
    DEFENDER_SETTINGS_COOLDOWN = 25
    DEFENDER_SETTINGS_SHIELD_CHANCE = {15,18,23}
    DEFENDER_SETTINGS_BLOCK_DAMAGE = 650
    DEFENDER_SETTINGS_ROOTED_DURATION = 2
    DEFENDER_SETTINGS_ROOTED_RADIUS = 700
    DEFENDER_SETTINGS_SHIELD_DURATION = {10,15,20}

    -- Immortal
    IMMORTAL_SETTINGS_CHANCE_RESPAWN = {13,20,23}
    IMMORTAL_SETTINGS_CHANCE_EXPLOSION = {35,45,50}
    IMMORTAL_SETTINGS_DAMAGE = {720,890,1400}
    IMMORTAL_SETTINGS_CHANCE_BKB = {10,20,30}
    IMMORTAL_SETTINGS_DURATION_BKB = {2,3,4}
    IMMORTAL_SETTINGS_COOLDOWN_BKB = {60,55,50}

    -- Himaron
    HIMARON_SETTINGS_CHANCE = {20,35,50}
    HIMARON_SETTINGS_DAMAGE = 150
    HIMARON_SETTINGS_MOVESPEED = 150
    HIMARON_SETTINGS_COOLDOWN_REDUCTION = 28
    HIMARON_SETTINGS_SPELL_AMPLIFY = 25
    HIMARON_SETTINGS_PURE_DAMAGE_INCREASE = {25,35,45}
    HIMARON_SETTINGS_COOLDOWN = 16
    HIMARON_SETTINGS_DURATION = 12
    DEMON_SETTINGS_CHANCE = {15,22,35}
    DEMON_SETTINGS_MIN_DAMAGE = {650,850,1800}
    DEMON_SETTINGS_MAX_DAMAGE = {740,1230,2600}
    DEMON_SETTINGS_INCREASE_DAMAGE_SELF = 20
    HIMARON_SWORD_COOLDOWN = 15

    -- Процент уровня
    PERCENT_OF_LEVEL_MINUTE = 210

    -- Сколько дают доп. киллов за нажатие на старте
    HOW_MUCH_KILLS_ADD = 2

    DASH_RESPAWN_TIME_LEVEL = 
    {
        {8, 8},
        {15, 9},
        {28, 10},
        {30, 10},
    }

    REROLL_SPHERES = 1
    NEW_SPHERES = 220
    MAX_SPHERE_LEVEL = 4
    COUNT_SPHERE_CHOICE = 2
    MAX_SPHERE_COUNT = 14
    
end

-- Фонтан эффект скорости
FOUNTAIN_AURA_RADIUS = 1500
FOUNTAIN_BONUS_MOVESPEED = 250
FOUNTAIN_DELAY_MODIFIER = 1.5

-- Задержка до начала игры
START_GAME_FREEZE_TIME = 12

-- Защитники флагов
UPGRADE_TIME_CHECK = 1.1 -- каждые 1 минут
UPGRADE_DAMAGE = 55
UPGRADE_HEALTH = 280
UPGRADE_ARMOR = 1

-- Время игры в секундах
GAME_TIME_CLOCK = 1080

-- Не отображать выбор скиллов этому герою
HEROES_SELECT_SPELL_DISABLED = 
{
    -- ["npc_dota_hero_invoker"] = true,
}

-- Не отображать выбор ультимейтов этому герою
HEROES_SELECT_ULTIMATE_DISABLED =
{
  ["npc_dota_hero_tinker"] = true
}

-- Настройки прыжка
JUMP_COOLDOWN = 0.5 -- ПЕРЕЗАРЯДКА ПРЫЖКА
JUMP_SPEED = 430 -- СКОРОСТЬ ПРЫЖКА
JUMP_HEIGHT = 98 -- ВЫСОТА ПРЫЖКА
JUMP_DISTANCE = 230 -- ДИСТАНЦИЯ ПРЫЖКА


-- ДЛЯ ЧЕНА ( 2 СКИЛЛ, ЛВЛ ЕГО КРИПОВ)
creep_ability_level_from_time = {
    {0, 1},       -- С 0 секунды крипы имеют уровень 1
    {200, 2},     -- С 5 минуты (300 секунд) крипы имеют уровень 2
    {400, 3},     -- С 10 минуты крипы имеют уровень 3
    {500, 4},     -- С 15 минуты крипы имеют уровень 4
    {650, 5},    -- С 20 минуты крипы имеют уровень 5
}