require('settings/game_settings')
require('settings/balance_settings')

-- Модификаторы
LinkLuaModifier('modifier_warsong_movespeed_bonus', 'modifiers/modifier_warsong_movespeed_bonus', LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier('modifier_warsong_movespeed_bonus_resistance_bonus', 'modifiers/modifier_warsong_movespeed_bonus_resistance_bonus', LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier('modifier_warsong_soldier_upgrade', 'modifiers/modifier_warsong_soldier_upgrade', LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier('modifier_warsong_minimap_icon', 'modifiers/modifier_warsong_minimap_icon', LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier('modifier_freeze_time_start', 'modifiers/modifier_freeze_time_start', LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier('modifier_nevermore_souls', 'modifiers/modifier_nevermore_souls', 0)
LinkLuaModifier('modifier_morphling_boss_delay_spawn', 'modifiers/modifier_morphling_boss_delay_spawn', LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier('modifier_morphling_boss_thinker_spawn', 'modifiers/modifier_morphling_boss_thinker_spawn', LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier('modifier_morphling_boss_thinker_spawn_stun', 'modifiers/modifier_morphling_boss_thinker_spawn', LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier('modifier_warsong_fate_defender', 'modifiers/modifier_warsong_fate_defender', LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier('modifier_warsong_fate_immortal', 'modifiers/modifier_warsong_fate_immortal', LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier('modifier_warsong_fate_murder', 'modifiers/modifier_warsong_fate_murder', LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier('modifier_warsong_fate_one_punchman', 'modifiers/modifier_warsong_fate_one_punchman', LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier('modifier_warsong_fate_himaron', 'modifiers/modifier_warsong_fate_himaron', LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier('modifier_teleport_scroll_fast', 'modifiers/modifier_teleport_scroll_fast', LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier('modifier_dash_creep_amp', 'modifiers/modifier_dash_creep_amp', LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier('modifier_flower_book', 'modifiers/books/modifier_flower_book', LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier('modifier_magical_book', 'modifiers/books/modifier_magical_book', LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier('modifier_mystery_book', 'modifiers/books/modifier_mystery_book', LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier('modifier_old_book', 'modifiers/books/modifier_old_book', LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier('modifier_golden_book', 'modifiers/books/modifier_golden_book', LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier('modifier_spell_radius', 'modifiers/generic/modifier_spell_radius', LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier('modifier_spell_amp_magical', 'modifiers/generic/modifier_spell_amp_magical', LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier('modifier_spell_amp_pure', 'modifiers/generic/modifier_spell_amp_pure', LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier('modifier_custom_wear', 'modifiers/generic/modifier_custom_wear', LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier('modifier_ability_upgrades_controller', 'modifiers/generic/modifier_ability_upgrades_controller', LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier('modifier_true_sight_portal_aura', 'modifiers/modifier_true_sight_portal_aura', LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier('modifier_sphere_armor', 'modifiers/spheres/modifier_sphere_armor', LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier('modifier_sphere_cooldown', 'modifiers/spheres/modifier_sphere_cooldown', LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier('modifier_sphere_decrase_mr', 'modifiers/spheres/modifier_sphere_decrase_mr', LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier('modifier_sphere_heal', 'modifiers/spheres/modifier_sphere_heal', LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier('modifier_sphere_magic_resistance', 'modifiers/spheres/modifier_sphere_magic_resistance', LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier('modifier_sphere_miss', 'modifiers/spheres/modifier_sphere_miss', LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier('modifier_sphere_movespeed', 'modifiers/spheres/modifier_sphere_movespeed', LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier('modifier_sphere_radiance', 'modifiers/spheres/modifier_sphere_radiance', LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier('modifier_sphere_shield_physic', 'modifiers/spheres/modifier_sphere_shield_physic', LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier('modifier_sphere_spell_radius', 'modifiers/spheres/modifier_sphere_spell_radius', LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier('modifier_sphere_shield_magic', 'modifiers/spheres/modifier_sphere_shield_magic', LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier('modifier_sphere_shield_all', 'modifiers/spheres/modifier_sphere_shield_all', LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier('modifier_balance', 'modifiers/modifier_balance', LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier('modifier_cursed_leader', 'modifiers/modifier_cursed_leader', LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier('modifier_head_boss', 'modifiers/modifier_head_boss', LUA_MODIFIER_MOTION_NONE)
